name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '17', '18', '19', '20', '21', '22-ea' ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    # Gradle 8.X no longer uses a default repository for toolchains.
    - name: Preload JDK ${{ matrix.java-version }}
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Set up JDK 11
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle    

    - name: Build application
      run: |
        ./gradlew io.openliberty.java.internal_fat_${{ matrix.java-version }}:build

    - name: Verify application
      run: |
        ./.github/workflows/scripts/verifyArtifact.sh ${{ matrix.java-version }}

    - name: Repackage application
      run: |
        ./.github/workflows/scripts/repackageApplication.sh io.openliberty.java.internal_fat_${{ matrix.java-version }}/build/libs/io.openliberty.java.internal_fat_${{ matrix.java-version }}.war .jar
    
    - name: Upload application
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@013d2b89baa2f354c5ffec54c68bec4ab39a2534 #v3.1.2
      with:
        name: Applications
        path: io.openliberty.java.internal_fat_${{ matrix.java-version }}/build/libs/io.openliberty.java.internal_fat_${{ matrix.java-version }}.jar
        if-no-files-found: error
